<script setup>

</script>

<template>
  <div class="spinner" :style="`width: ${size}px; height: ${size}px`">
    <svg v-if="show"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(241, 242, 243, 0); display: block; shape-rendering: auto;" width="{{size}}px" height="{{size}}px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="30" cy="50" fill="#ffffff" r="20">
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
</circle>
<circle cx="70" cy="50" fill="#dc2626" r="20">
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="0s"></animate>
</circle>
<circle cx="30" cy="50" fill="#ffffff" r="20">
  <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
  <animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" dur="1s" repeatCount="indefinite"></animate>
</circle>
      <!-- [ldio] generated by https://loading.io/ --></svg>
  </div>
</template>

<script>
export default {
  name: 'spinner-component',

  props: {
    show: Boolean,
    size: {
      type: Number,
      default: 20
    }
  },
}

</script>

<style scoped lang="sass">

</style>